<div class='coluna total'>
    <div class="conteudo fundoTransparente">
        <h1>Seja Bem-Vindo ao Sistema e-Admin!</h1>
        <fieldset>
            <legend>Minhas Solicitações</legend>
            <table>
                <thead>
                    <tr>
                        <th>Solicitações</th>
                        <th>Quantidade</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="/app/e-Admin/sosti/minhassolicitacoes/avaliacao">Para Avaliação</a></td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td><a href="/app/e-Admin/sosti/minhassolicitacoes/pedidoinformacao">Com Solicitação de Informação</a></td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td><a href="/app/e-Admin/sosti/minhassolicitacoes/pedidoinformacaorespondido">Com Solicitação de Informação Respondida</a></td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td><a href="/app/e-Admin/sosti/minhassolicitacoes/atendimento">Em Atendimento</a></td>
                        <td>0</td>
                    </tr>
                </tbody></table>
        </fieldset>

        <fieldset>
            <legend>Minhas Notificações</legend>
            <table>
                <thead>
                    <tr>
                        <th >Notificações</th>
                        <th  >Quantidade</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="/app/e-Admin/admin/notificacoes/minhasnotificacoes">Não Lidas</a></td>
                        <td>0</td>
                    </tr>
                </tbody></table>
        </fieldset>

        <fieldset>
            <legend>Meus Avisos</legend>
            <table>
                <thead>
                    <tr>
                        <th >Avisos</th>
                        <th  >Quantidade</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="/app/e-Admin/sisad/caixaaviso/entrada">Não Lidos</a></td>
                        <td>0</td>
                    </tr>
                </tbody></table>
        </fieldset>
        <fieldset>
            <legend>Gráficos</legend>
            <table>
                <thead>
                    <tr>
                        <th colspan="2">Dashboard</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="/app/e-Admin/sosti/index">Sosti</a></td>
                        <td><a href="/app/e-Admin/sisad/index">Sisad</a></td>
                    </tr>
                </tbody></table>
        </fieldset>    
    </div>
</div>