
<table>
    <caption>t&iacute;tulo da tabela &lt;caption&gt;</caption>
    <thead>
        <tr>
            <th>&lt;thead&gt; t&iacute;tulo de cabe&ccedil;alho coluna1</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>&lt;tfoot&gt; rodap&eacute; coluna 1</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>&lt;tbody&gt; conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr class="ativa">
            <td>conte&uacute;do lcoluna 1 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
    </tbody>
</table>

<table class="noFixa">
    <caption>t&iacute;tulo da tabela &lt;caption&gt; - <span>class noFixa</span></caption>
    <thead>
        <tr>
            <th>&lt;thead&gt; t&iacute;tulo de cabe&ccedil;alho coluna1</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>&lt;tfoot&gt; rodap&eacute; coluna 1</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>&lt;tbody&gt; conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr class="ativa">
            <td>conte&uacute;do lcoluna 1 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
    </tbody>
</table>


<table class="fixaCabecalho" >
    <caption>t&iacute;tulo da tabela &lt;caption&gt;- <span>class fixaCabecalho</span></caption>
    <thead>
        <tr>
            <th>&lt;thead&gt; t&iacute;tulo de cabe&ccedil;alho coluna1</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
            <th>t&iacute;tulo de cabe&ccedil;alho coluna2</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>&lt;tfoot&gt; rodap&eacute; coluna 1</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
            <td>rodap&eacute; coluna 2</td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>&lt;tbody&gt; conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr class="ativa">
            <td>conte&uacute;do lcoluna 1 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
            <td>conte&uacute;do lcoluna 2 ----- ativa</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
        <tr>
            <td>conte&uacute;do lcoluna 1</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
            <td>conte&uacute;do lcoluna 2</td>
        </tr>
    </tbody>
</table>
</div>	
</div>