<h1><?php echo $this->title; ?></h1>
<?php echo $this->tabelaAvisos; ?>
<?php if (count($this->data)): ?>
<table class="grid">
    <thead>
        <tr>
            <th ><a href="<?php echo $this->baseUrl(); ?>/sisad/fase-adm/index/ordem/FADM_DS_FASE/direcao/<?php echo $this->direcao ?> ">Descrição<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th ><a href="<?php echo $this->baseUrl(); ?>/sisad/fase-adm/index/ordem/FADM_IC_DCTO_FASE/direcao/<?php echo $this->direcao ?> ">Documento da Fase<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc'); ?>"></span></a></th>
        </tr>
    </thead>
     
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td><?php echo $this->escape($data->getDescricao()) ?></td>
            <td><?php echo $this->escape($data->getSituacao()) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="2">Total: <?php echo $this->data->getTotalItemCount() ?></td></tr></tfoot>
</table>
<?php echo $this->paginationControl($this->data, null, null, null)
//-- pagination
//-- style
//-- partial
//-- data
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif;