<?php if ($this->pageCount): ?>
    <?php $params = array('page' => null)?>
    <div class="paginationControl" style="text-align:center">
        <?php if (isset($this->previous)): ?>
            <?php $params['page'] = $this->first?>
            <a href="<?php echo $this->url($params); ?>">
                <?php echo 'Primeira' ?>
            </a>
             <?php $params['page'] = $this->previous?>
            <a href="<?php echo $this->url($params); ?>">
                &lt; <?php echo 'Anterior' ?>
            </a> 
        <?php else: ?>
            <span class="disabled"><?php echo 'Primeira' ?></span> 
            <span class="disabled">&lt; <?php echo 'Anterior' ?></span> 
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <?php $params['page'] = $page?>
                <a href="<?php echo $this->url($params); ?>"><?php echo $page; ?></a> 
            <?php else: ?>
                <span class="disabled"><?php echo $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <?php $params['page'] = $this->next?>
            <a href="<?php echo $this->url($params); ?>">
                <?php echo 'Próxima' ?>  &gt;
            </a>
            <?php $params['page'] = $this->last?>
            <a href="<?php echo $this->url($params); ?>">
                <?php echo 'Última' ?> 
            </a>
        <?php else: ?>
            <span class="disabled"><?php echo 'Próxima' ?> &gt;</span>
            <span class="disabled"><?php echo 'Última' ?> </span>
        <?php endif; ?>
    </div>
<?php endif; ?>