<?php echo $this->render("_partials/topLogin.php"); ?>

<div id="container">
    <div id="conteudo">
        <div class="coluna total">
            <section>
                <article>
                    <div class="conteudo fundoTransparente">
                        <?php echo $this->layout()->content; ?>
                    </div><!--conteudo article-->
                </article>
            </section>
        </div><!-- div section -->
    </div><!--conteudo geral-->
</div><!--container-->

<?php echo $this->render("_partials/footerLogin.php"); ?>
