<h2> Servidor </h2>

<h3> Dados do servidor </h3>
<p>
<strong>Sistema operacional</strong>: <?php echo $this->servidorSo; ?><br />
<strong>Nome</strong>: <?php echo $this->servidorNome; ?><br />
<strong>IP</strong>: <?php echo $this->servidorIp; ?>
<?php echo $this->servidor; ?>
</p>

<h3> Apache </h3>
<p><strong>Versão</strong>: <?php echo $this->apache; ?></p>

<h3> PHP </h3>
<p><strong>Versão</strong>: <?php echo $this->php; ?></p>

<h3> Zend </h3>
<p>
<strong>Framework</strong>: <?php echo $this->zendFramework; ?> <br />
<strong>Engine</strong>: <?php echo $this->zendEngine; ?>
</p>

<h2> Local </h2>

<h3> Navegador </h3>
<p><strong>Tipo / versão</strong>: <?php echo $this->navegador; ?>
